/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 book.glb --transform 
Files: book.glb [321.14KB] > /Users/connorhansen/code/bookshelf/public/models/book-transformed.glb [37.01KB] (88%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/book-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.Base} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.Cover} />
      <mesh
        geometry={nodes.Cube001_2.geometry}
        material={materials["Material.003"]}
      />
    </group>
  );
}

useGLTF.preload("/book-transformed.glb");
