/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 book.glb --transform 
Files: book.glb [127.1KB] > /Users/connorhansen/code/bookshelf/public/models/book-transformed.glb [15.49KB] (88%)
*/

import React, { useRef } from "react";
import { useGLTF, Text } from "@react-three/drei";

export function Book(props) {
  const { nodes, materials } = useGLTF("/models/book-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.Base} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.Cover} />
      <mesh
        geometry={nodes.Cube001_2.geometry}
        material={materials["Material.003"]}
      />
      {/* Text on spine */}
      {/* TODO fix click events not firing on text */}
      <Text
        position={[0, 0, 2.01]} // offset to prevent z-clipping
        rotation={[Math.PI, Math.PI, Math.PI / 2]}
        fontSize={0.5}
        color="black"
        anchorX="center"
        anchorY="middle"
      >
        {props.title}
      </Text>
    </group>
  );
}

useGLTF.preload("/models/book-transformed.glb");
